name: Compile Firmware

on:
  push:
  pull_request:
  workflow_call:

jobs:
  compile-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: cd firmware && pio run
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware/.pio/build/pico/firmware.uf2