name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    name: Publish binaries
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download firmware artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware
    - name: Download case artifact
      uses: actions/download-artifact@v4
      with:
        name: case
    - name: Download buttons artifact
      uses: actions/download-artifact@v4
      with:
        name: buttons
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      permissions:
        contents: write
      with:
          files: |
            *.uf2
            *.stl